pipeline:
  name: Demo Harness
  identifier: Demo_Harness
  projectIdentifier: FirstHarness
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHubconecter
        repoName: GHA-java-poc-sync
        build: <+input>
  stages:
    - stage:
        name: Maven-Build
        identifier: MavenBuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Hello Harness
                  identifier: Hello_Harness
                  spec:
                    shell: Sh
                    command: echo "Hello Harness"
              - step:
                  type: Run
                  name: Build with Maven
                  identifier: Build_Maven
                  spec:
                    connectorRef: account.DockerHubReg
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean compile
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    connectorRef: account.DockerHubReg
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean test
              - step:
                  type: Run
                  name: Artifactory
                  identifier: Artifactory
                  spec:
                    connectorRef: account.DockerHubReg
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean Artifactory
